"""Add player_base_price to AuctionEvent

Revision ID: 01d8b47714c9
Revises: 8c5cb775365f
Create Date: 2026-03-13 06:05:56.579431

"""
from alembic import op
import sqlalchemy as sa


revision = '01d8b47714c9'
down_revision = '8c5cb775365f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_events', sa.Column('player_base_price', sa.Integer(), nullable=False, server_default='100'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_events', 'player_base_price')
    # ### end Alembic commands ###
