"""Add team_budget and team_max_players to AuctionEvent

Revision ID: 8c5cb775365f
Revises: a2de85309837
Create Date: 2026-03-13 05:16:01.034474

"""
from alembic import op
import sqlalchemy as sa


revision = '8c5cb775365f'
down_revision = 'a2de85309837'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('auction_events', sa.Column('team_budget', sa.Integer(), nullable=False, server_default='100000'))
    op.add_column('auction_events', sa.Column('team_max_players', sa.Integer(), nullable=False, server_default='15'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('auction_events', 'team_max_players')
    op.drop_column('auction_events', 'team_budget')
    # ### end Alembic commands ###
